baseURL = "/"
defaultContentLanguage = "zh-cn"
languageCode = "zh_CN"
title = "My New Hugo Site"

theme = "hugo-theme-meghna"

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

[Language]

[Languages.zh-cn]
languageName = "简体中文"
languageCode = "zh_CN"
# contentDir = "content/english"
weight = 1
home = "首页"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

    [[Languages.zh-cn.menu.main]]
    name = "关于"
    pre = "#"
    url = "about"
    weight = 1

    [[Languages.zh-cn.menu.main]]
    name = "服务与支持"
    pre = "#"
    url = "services"
    weight = 2

    [[Languages.zh-cn.menu.main]]
    name = "作品展示"
    pre = "#"
    url = "portfolio"
    weight = 3

    [[Languages.zh-cn.menu.main]]
    name = "团队介绍"
    pre = "#"
    url = "team"
    weight = 4

    [[Languages.zh-cn.menu.main]]
    name = "产品定价"
    pre = "#"
    url = "pricing"
    weight = 5

    [[Languages.zh-cn.menu.main]]
    name = "最新动态"
    pre = "#"
    url = "blog"
    weight = 6

    [[Languages.zh-cn.menu.main]]
    name = "联系我们"
    pre = "#"
    url = "contact"
    weight = 7

    [Languages.zh-cn.params]
    logo = "images/logo.png"
    # Meta data
    description = "广州知一尚智科技有限公司官网"
    author = "zhiyishangzhi"
    # Google Analytics
    google_analytics_id = "" # Your ID
    # post share
    post_share = true

      # preloader
      [Languages.zh-cn.params.preloader]
      enable = false
      preloader = "images/logo.png"

      # cookies
      [Languages.zh-cn.params.cookies]
      enable = false
      expire_days = 2

      # google map
      [Languages.zh-cn.params.map]
      enable = false
      gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
      map_latitude = "51.5223477"
      map_longitude = "-0.1622023"
      map_marker = "images/marker.png"

[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"


      [[Languages.en.menu.main]]
      name = "about"
      pre = "#"
      url = "about"
      weight = 1

      [[Languages.en.menu.main]]
      name = "services"
      pre = "#"
      url = "services"
      weight = 2

      [[Languages.en.menu.main]]
      name = "portfolio"
      pre = "#"
      url = "portfolio"
      weight = 3

      [[Languages.en.menu.main]]
      name = "team"
      pre = "#"
      url = "team"
      weight = 4

      [[Languages.en.menu.main]]
      name = "pricing"
      pre = "#"
      url = "pricing"
      weight = 5

      [[Languages.en.menu.main]]
      name = "blog"
      pre = "#"
      url = "blog"
      weight = 6

      [[Languages.en.menu.main]]
      name = "contact"
      pre = "#"
      url = "contact"
      weight = 7


[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

      [[Languages.fr.menu.main]]
      name = "sur"
      pre = "#"
      url = "about"
      weight = 1

      [[Languages.fr.menu.main]]
      name = "un service"
      pre = "#"
      url = "services"
      weight = 2

      [[Languages.fr.menu.main]]
      name = "portefeuille"
      pre = "#"
      url = "portfolio"
      weight = 3

      [[Languages.fr.menu.main]]
      name = "équipe"
      pre = "#"
      url = "team"
      weight = 4

      [[Languages.fr.menu.main]]
      name = "tarification"
      pre = "#"
      url = "pricing"
      weight = 5

      [[Languages.fr.menu.main]]
      name = "blog"
      pre = "#"
      url = "blog"
      weight = 6

      [[Languages.fr.menu.main]]
      name = "contact"
      pre = "#"
      url = "contact"
      weight = 7


    [Languages.fr.params]
    logo = "images/logo.png"
    # Meta data
    description = "广州知一尚智科技有限公司官网"
    author = "zhiyishangzhi"
    # Google Analytics
    google_analytics_id = "" # Your ID
    # post share
    post_share = true

      # preloader
      [Languages.fr.params.preloader]
      enable = false
      preloader = "images/logo.png"

      # cookies
      [Languages.fr.params.cookies]
      enable = false
      expire_days = 2

      # google map
      [Languages.fr.params.map]
      enable = false
      gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
      map_latitude = "51.5223477"
      map_longitude = "-0.1622023"
      map_marker = "images/marker.png"


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

  # preloader
  [params.preloader]
  enable = false
  preloader = "images/logo.png"

  # cookies
  [params.cookies]
  enable = false
  expire_days = 2

  # google map
  [params.map]
  enable = false
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
  map_latitude = "51.5223477"
  map_longitude = "-0.1622023"
  map_marker = "images/marker.png"

  ############################# social icons ##########################
  [[params.social]]
  icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
  link = "#"
